/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimpananRouteImport } from './routes/_app.simpanan'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnggotaRouteImport } from './routes/_app.anggota'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimpananRoute = AppSimpananRouteImport.update({
  id: '/simpanan',
  path: '/simpanan',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnggotaRoute = AppAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/anggota': typeof AppAnggotaRoute
  '/dashboard': typeof AppDashboardRoute
  '/simpanan': typeof AppSimpananRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/anggota': typeof AppAnggotaRoute
  '/dashboard': typeof AppDashboardRoute
  '/simpanan': typeof AppSimpananRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_app/anggota': typeof AppAnggotaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/simpanan': typeof AppSimpananRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/unlock' | '/anggota' | '/dashboard' | '/simpanan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/unlock' | '/anggota' | '/dashboard' | '/simpanan'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/unlock'
    | '/_app/anggota'
    | '/_app/dashboard'
    | '/_app/simpanan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simpanan': {
      id: '/_app/simpanan'
      path: '/simpanan'
      fullPath: '/simpanan'
      preLoaderRoute: typeof AppSimpananRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anggota': {
      id: '/_app/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AppAnggotaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnggotaRoute: typeof AppAnggotaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSimpananRoute: typeof AppSimpananRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnggotaRoute: AppAnggotaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSimpananRoute: AppSimpananRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
