/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimpananRouteImport } from './routes/_app.simpanan'
import { Route as AppPinjamanRouteImport } from './routes/_app.pinjaman'
import { Route as AppLaporanRouteImport } from './routes/_app.laporan'
import { Route as AppDatabaseRouteImport } from './routes/_app.database'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnggotaRouteImport } from './routes/_app.anggota'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppPinjamanIdRouteImport } from './routes/_app.pinjaman_.$id'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimpananRoute = AppSimpananRouteImport.update({
  id: '/simpanan',
  path: '/simpanan',
  getParentRoute: () => AppRoute,
} as any)
const AppPinjamanRoute = AppPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanRoute = AppLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnggotaRoute = AppAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPinjamanIdRoute = AppPinjamanIdRouteImport.update({
  id: '/pinjaman_/$id',
  path: '/pinjaman/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof AppAdminRoute
  '/anggota': typeof AppAnggotaRoute
  '/dashboard': typeof AppDashboardRoute
  '/database': typeof AppDatabaseRoute
  '/laporan': typeof AppLaporanRoute
  '/pinjaman': typeof AppPinjamanRoute
  '/simpanan': typeof AppSimpananRoute
  '/pinjaman/$id': typeof AppPinjamanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof AppAdminRoute
  '/anggota': typeof AppAnggotaRoute
  '/dashboard': typeof AppDashboardRoute
  '/database': typeof AppDatabaseRoute
  '/laporan': typeof AppLaporanRoute
  '/pinjaman': typeof AppPinjamanRoute
  '/simpanan': typeof AppSimpananRoute
  '/pinjaman/$id': typeof AppPinjamanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/anggota': typeof AppAnggotaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/database': typeof AppDatabaseRoute
  '/_app/laporan': typeof AppLaporanRoute
  '/_app/pinjaman': typeof AppPinjamanRoute
  '/_app/simpanan': typeof AppSimpananRoute
  '/_app/pinjaman_/$id': typeof AppPinjamanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/admin'
    | '/anggota'
    | '/dashboard'
    | '/database'
    | '/laporan'
    | '/pinjaman'
    | '/simpanan'
    | '/pinjaman/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/admin'
    | '/anggota'
    | '/dashboard'
    | '/database'
    | '/laporan'
    | '/pinjaman'
    | '/simpanan'
    | '/pinjaman/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/unlock'
    | '/_app/admin'
    | '/_app/anggota'
    | '/_app/dashboard'
    | '/_app/database'
    | '/_app/laporan'
    | '/_app/pinjaman'
    | '/_app/simpanan'
    | '/_app/pinjaman_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simpanan': {
      id: '/_app/simpanan'
      path: '/simpanan'
      fullPath: '/simpanan'
      preLoaderRoute: typeof AppSimpananRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pinjaman': {
      id: '/_app/pinjaman'
      path: '/pinjaman'
      fullPath: '/pinjaman'
      preLoaderRoute: typeof AppPinjamanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan': {
      id: '/_app/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AppLaporanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database': {
      id: '/_app/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anggota': {
      id: '/_app/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AppAnggotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pinjaman_/$id': {
      id: '/_app/pinjaman_/$id'
      path: '/pinjaman/$id'
      fullPath: '/pinjaman/$id'
      preLoaderRoute: typeof AppPinjamanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnggotaRoute: typeof AppAnggotaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppLaporanRoute: typeof AppLaporanRoute
  AppPinjamanRoute: typeof AppPinjamanRoute
  AppSimpananRoute: typeof AppSimpananRoute
  AppPinjamanIdRoute: typeof AppPinjamanIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnggotaRoute: AppAnggotaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabaseRoute: AppDatabaseRoute,
  AppLaporanRoute: AppLaporanRoute,
  AppPinjamanRoute: AppPinjamanRoute,
  AppSimpananRoute: AppSimpananRoute,
  AppPinjamanIdRoute: AppPinjamanIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
